require "plugin-config.impatient"
require "plugin-config.treesetter"
require "plugin-config.bufferline"
require "plugin-config.whichkey"
require "plugin-config.lualine"
require "plugin-config.autopairs"
require "plugin-config.trouble"
require "plugin-config.gitsigns"
-- require "plugin-config.navigator"
require "plugin-config.nvim-comment"
require "plugin-config.toggleterm"
require "plugin-config.file-explorer"
require "plugin-config.autosave"
